// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXpBg0iYU7gbQJyOfE4Q391ql31ZrRDE',
    appId: '1:296863879968:web:c4ff23ff466ff5d9f2fd45',
    messagingSenderId: '296863879968',
    projectId: 'datingapplogin-f9528',
    authDomain: 'datingapplogin-f9528.firebaseapp.com',
    storageBucket: 'datingapplogin-f9528.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj4BU_0B_13jrE914A5Lz23-1CsHlNDRA',
    appId: '1:296863879968:android:1d4dcf9544c80c71f2fd45',
    messagingSenderId: '296863879968',
    projectId: 'datingapplogin-f9528',
    storageBucket: 'datingapplogin-f9528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpsBpRQZhF0N4X7i7CmrGTz_1sxXChfpY',
    appId: '1:296863879968:ios:8cf21063f6c28fc7f2fd45',
    messagingSenderId: '296863879968',
    projectId: 'datingapplogin-f9528',
    storageBucket: 'datingapplogin-f9528.appspot.com',
    iosClientId: '296863879968-0rr597gs2egb7k1r2lgluru6vs5egucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpsBpRQZhF0N4X7i7CmrGTz_1sxXChfpY',
    appId: '1:296863879968:ios:8cf21063f6c28fc7f2fd45',
    messagingSenderId: '296863879968',
    projectId: 'datingapplogin-f9528',
    storageBucket: 'datingapplogin-f9528.appspot.com',
    iosClientId: '296863879968-0rr597gs2egb7k1r2lgluru6vs5egucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
